apiVersion: batch/v1
kind: CronJob
metadata:
  name: callserviceb
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: callserviceb
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl "http://serviceb-app.default.svc.cluster.local:8082/api/serviceB"
          restartPolicy: OnFailure
