apiVersion: v1
kind: Service
metadata:
  name: {{ include "appserviceb.fullname" . }}
  labels:
    app: serviceb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
      app: serviceb

